import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [
        {
            type: 'category',
            label: 'Introduction',
            items: ['intro', 'getting-started', 'architecture'],
        },
        {
            type: 'category',
            label: 'Backend',
            items: [
                'backend/authentication',
                'backend/multitenancy',
                'backend/permissions',
                'backend/audit-logging',
                'backend/company-license-limits',
            ],
        },
        {
            type: 'category',
            label: 'Frontend',
            items: ['frontend/react-inertia', 'frontend/components'],
        },
        {
            type: 'category',
            label: 'Development Guide',
            items: ['development-guide', 'resource-module-guide', 'module-creation-checklist', 'troubleshooting-guide'],
        },
        {
            type: 'category',
            label: 'API Reference',
            items: [{ type: 'autogenerated', dirName: 'api' }],
        },
    ],

    // But you can create a sidebar manually
    /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
